// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.IncomeProfile;
import javax.persistence.Entity;

privileged aspect IncomeProfile_Roo_Jpa_Entity {
    
    declare @type: IncomeProfile: @Entity;
    
}
