// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.TimingProfile;
import javax.persistence.Entity;

privileged aspect TimingProfile_Roo_Jpa_Entity {
    
    declare @type: TimingProfile: @Entity;
    
}
