// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.AgeProfile;
import com.advmon.webapp.datamodel.profiles.AgeProfileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AgeProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AgeProfileDataOnDemand: @Component;
    
    private Random AgeProfileDataOnDemand.rnd = new SecureRandom();
    
    private List<AgeProfile> AgeProfileDataOnDemand.data;
    
    public AgeProfile AgeProfileDataOnDemand.getNewTransientAgeProfile(int index) {
        AgeProfile obj = new AgeProfile();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void AgeProfileDataOnDemand.setDescription(AgeProfile obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void AgeProfileDataOnDemand.setName(AgeProfile obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public AgeProfile AgeProfileDataOnDemand.getSpecificAgeProfile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AgeProfile obj = data.get(index);
        Long id = obj.getId();
        return AgeProfile.findAgeProfile(id);
    }
    
    public AgeProfile AgeProfileDataOnDemand.getRandomAgeProfile() {
        init();
        AgeProfile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AgeProfile.findAgeProfile(id);
    }
    
    public boolean AgeProfileDataOnDemand.modifyAgeProfile(AgeProfile obj) {
        return false;
    }
    
    public void AgeProfileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AgeProfile.findAgeProfileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AgeProfile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AgeProfile>();
        for (int i = 0; i < 10; i++) {
            AgeProfile obj = getNewTransientAgeProfile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
