// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.AgeProfile;
import com.advmon.webapp.datamodel.profiles.AgeProfileDataOnDemand;
import com.advmon.webapp.datamodel.profiles.AgeProfileIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgeProfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AgeProfileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AgeProfileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AgeProfileIntegrationTest: @Transactional;
    
    @Autowired
    AgeProfileDataOnDemand AgeProfileIntegrationTest.dod;
    
    @Test
    public void AgeProfileIntegrationTest.testCountAgeProfiles() {
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", dod.getRandomAgeProfile());
        long count = AgeProfile.countAgeProfiles();
        Assert.assertTrue("Counter for 'AgeProfile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AgeProfileIntegrationTest.testFindAgeProfile() {
        AgeProfile obj = dod.getRandomAgeProfile();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to provide an identifier", id);
        obj = AgeProfile.findAgeProfile(id);
        Assert.assertNotNull("Find method for 'AgeProfile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AgeProfile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AgeProfileIntegrationTest.testFindAllAgeProfiles() {
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", dod.getRandomAgeProfile());
        long count = AgeProfile.countAgeProfiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'AgeProfile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AgeProfile> result = AgeProfile.findAllAgeProfiles();
        Assert.assertNotNull("Find all method for 'AgeProfile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AgeProfile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AgeProfileIntegrationTest.testFindAgeProfileEntries() {
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", dod.getRandomAgeProfile());
        long count = AgeProfile.countAgeProfiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AgeProfile> result = AgeProfile.findAgeProfileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AgeProfile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AgeProfile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AgeProfileIntegrationTest.testFlush() {
        AgeProfile obj = dod.getRandomAgeProfile();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to provide an identifier", id);
        obj = AgeProfile.findAgeProfile(id);
        Assert.assertNotNull("Find method for 'AgeProfile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAgeProfile(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AgeProfile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AgeProfileIntegrationTest.testMergeUpdate() {
        AgeProfile obj = dod.getRandomAgeProfile();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to provide an identifier", id);
        obj = AgeProfile.findAgeProfile(id);
        boolean modified =  dod.modifyAgeProfile(obj);
        Integer currentVersion = obj.getVersion();
        AgeProfile merged = (AgeProfile)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AgeProfile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AgeProfileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", dod.getRandomAgeProfile());
        AgeProfile obj = dod.getNewTransientAgeProfile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AgeProfile' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AgeProfile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AgeProfileIntegrationTest.testRemove() {
        AgeProfile obj = dod.getRandomAgeProfile();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AgeProfile' failed to provide an identifier", id);
        obj = AgeProfile.findAgeProfile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AgeProfile' with identifier '" + id + "'", AgeProfile.findAgeProfile(id));
    }
    
}
