// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.EducationProfile;
import com.advmon.webapp.datamodel.profiles.EducationProfileDataOnDemand;
import com.advmon.webapp.datamodel.profiles.EducationProfileIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EducationProfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EducationProfileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EducationProfileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EducationProfileIntegrationTest: @Transactional;
    
    @Autowired
    EducationProfileDataOnDemand EducationProfileIntegrationTest.dod;
    
    @Test
    public void EducationProfileIntegrationTest.testCountEducationProfiles() {
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", dod.getRandomEducationProfile());
        long count = EducationProfile.countEducationProfiles();
        Assert.assertTrue("Counter for 'EducationProfile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EducationProfileIntegrationTest.testFindEducationProfile() {
        EducationProfile obj = dod.getRandomEducationProfile();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to provide an identifier", id);
        obj = EducationProfile.findEducationProfile(id);
        Assert.assertNotNull("Find method for 'EducationProfile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EducationProfile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EducationProfileIntegrationTest.testFindAllEducationProfiles() {
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", dod.getRandomEducationProfile());
        long count = EducationProfile.countEducationProfiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'EducationProfile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EducationProfile> result = EducationProfile.findAllEducationProfiles();
        Assert.assertNotNull("Find all method for 'EducationProfile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EducationProfile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EducationProfileIntegrationTest.testFindEducationProfileEntries() {
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", dod.getRandomEducationProfile());
        long count = EducationProfile.countEducationProfiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EducationProfile> result = EducationProfile.findEducationProfileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EducationProfile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EducationProfile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EducationProfileIntegrationTest.testFlush() {
        EducationProfile obj = dod.getRandomEducationProfile();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to provide an identifier", id);
        obj = EducationProfile.findEducationProfile(id);
        Assert.assertNotNull("Find method for 'EducationProfile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEducationProfile(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EducationProfile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EducationProfileIntegrationTest.testMergeUpdate() {
        EducationProfile obj = dod.getRandomEducationProfile();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to provide an identifier", id);
        obj = EducationProfile.findEducationProfile(id);
        boolean modified =  dod.modifyEducationProfile(obj);
        Integer currentVersion = obj.getVersion();
        EducationProfile merged = (EducationProfile)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EducationProfile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EducationProfileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", dod.getRandomEducationProfile());
        EducationProfile obj = dod.getNewTransientEducationProfile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EducationProfile' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EducationProfile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EducationProfileIntegrationTest.testRemove() {
        EducationProfile obj = dod.getRandomEducationProfile();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EducationProfile' failed to provide an identifier", id);
        obj = EducationProfile.findEducationProfile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EducationProfile' with identifier '" + id + "'", EducationProfile.findEducationProfile(id));
    }
    
}
