// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.InterestProfile;
import com.advmon.webapp.datamodel.profiles.InterestProfileDataOnDemand;
import com.advmon.webapp.datamodel.profiles.InterestProfileIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InterestProfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InterestProfileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InterestProfileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: InterestProfileIntegrationTest: @Transactional;
    
    @Autowired
    InterestProfileDataOnDemand InterestProfileIntegrationTest.dod;
    
    @Test
    public void InterestProfileIntegrationTest.testCountInterestProfiles() {
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", dod.getRandomInterestProfile());
        long count = InterestProfile.countInterestProfiles();
        Assert.assertTrue("Counter for 'InterestProfile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InterestProfileIntegrationTest.testFindInterestProfile() {
        InterestProfile obj = dod.getRandomInterestProfile();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to provide an identifier", id);
        obj = InterestProfile.findInterestProfile(id);
        Assert.assertNotNull("Find method for 'InterestProfile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'InterestProfile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InterestProfileIntegrationTest.testFindAllInterestProfiles() {
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", dod.getRandomInterestProfile());
        long count = InterestProfile.countInterestProfiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'InterestProfile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<InterestProfile> result = InterestProfile.findAllInterestProfiles();
        Assert.assertNotNull("Find all method for 'InterestProfile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'InterestProfile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InterestProfileIntegrationTest.testFindInterestProfileEntries() {
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", dod.getRandomInterestProfile());
        long count = InterestProfile.countInterestProfiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<InterestProfile> result = InterestProfile.findInterestProfileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'InterestProfile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'InterestProfile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InterestProfileIntegrationTest.testFlush() {
        InterestProfile obj = dod.getRandomInterestProfile();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to provide an identifier", id);
        obj = InterestProfile.findInterestProfile(id);
        Assert.assertNotNull("Find method for 'InterestProfile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInterestProfile(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'InterestProfile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InterestProfileIntegrationTest.testMergeUpdate() {
        InterestProfile obj = dod.getRandomInterestProfile();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to provide an identifier", id);
        obj = InterestProfile.findInterestProfile(id);
        boolean modified =  dod.modifyInterestProfile(obj);
        Integer currentVersion = obj.getVersion();
        InterestProfile merged = (InterestProfile)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'InterestProfile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InterestProfileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", dod.getRandomInterestProfile());
        InterestProfile obj = dod.getNewTransientInterestProfile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'InterestProfile' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'InterestProfile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InterestProfileIntegrationTest.testRemove() {
        InterestProfile obj = dod.getRandomInterestProfile();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InterestProfile' failed to provide an identifier", id);
        obj = InterestProfile.findInterestProfile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'InterestProfile' with identifier '" + id + "'", InterestProfile.findInterestProfile(id));
    }
    
}
