// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.InterestProfile;
import com.advmon.webapp.datamodel.profiles.InterestProfileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect InterestProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InterestProfileDataOnDemand: @Component;
    
    private Random InterestProfileDataOnDemand.rnd = new SecureRandom();
    
    private List<InterestProfile> InterestProfileDataOnDemand.data;
    
    public InterestProfile InterestProfileDataOnDemand.getNewTransientInterestProfile(int index) {
        InterestProfile obj = new InterestProfile();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void InterestProfileDataOnDemand.setDescription(InterestProfile obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void InterestProfileDataOnDemand.setName(InterestProfile obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public InterestProfile InterestProfileDataOnDemand.getSpecificInterestProfile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        InterestProfile obj = data.get(index);
        Long id = obj.getId();
        return InterestProfile.findInterestProfile(id);
    }
    
    public InterestProfile InterestProfileDataOnDemand.getRandomInterestProfile() {
        init();
        InterestProfile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return InterestProfile.findInterestProfile(id);
    }
    
    public boolean InterestProfileDataOnDemand.modifyInterestProfile(InterestProfile obj) {
        return false;
    }
    
    public void InterestProfileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = InterestProfile.findInterestProfileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'InterestProfile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<InterestProfile>();
        for (int i = 0; i < 10; i++) {
            InterestProfile obj = getNewTransientInterestProfile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
