// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.LanguageProfile;
import com.advmon.webapp.datamodel.profiles.LanguageProfileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LanguageProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LanguageProfileDataOnDemand: @Component;
    
    private Random LanguageProfileDataOnDemand.rnd = new SecureRandom();
    
    private List<LanguageProfile> LanguageProfileDataOnDemand.data;
    
    public LanguageProfile LanguageProfileDataOnDemand.getNewTransientLanguageProfile(int index) {
        LanguageProfile obj = new LanguageProfile();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void LanguageProfileDataOnDemand.setDescription(LanguageProfile obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void LanguageProfileDataOnDemand.setName(LanguageProfile obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public LanguageProfile LanguageProfileDataOnDemand.getSpecificLanguageProfile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LanguageProfile obj = data.get(index);
        Long id = obj.getId();
        return LanguageProfile.findLanguageProfile(id);
    }
    
    public LanguageProfile LanguageProfileDataOnDemand.getRandomLanguageProfile() {
        init();
        LanguageProfile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return LanguageProfile.findLanguageProfile(id);
    }
    
    public boolean LanguageProfileDataOnDemand.modifyLanguageProfile(LanguageProfile obj) {
        return false;
    }
    
    public void LanguageProfileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LanguageProfile.findLanguageProfileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LanguageProfile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LanguageProfile>();
        for (int i = 0; i < 10; i++) {
            LanguageProfile obj = getNewTransientLanguageProfile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
