// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.LocationProfile;
import com.advmon.webapp.datamodel.profiles.LocationProfileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LocationProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LocationProfileDataOnDemand: @Component;
    
    private Random LocationProfileDataOnDemand.rnd = new SecureRandom();
    
    private List<LocationProfile> LocationProfileDataOnDemand.data;
    
    public LocationProfile LocationProfileDataOnDemand.getNewTransientLocationProfile(int index) {
        LocationProfile obj = new LocationProfile();
        setCity(obj, index);
        setCountry(obj, index);
        setDescription(obj, index);
        setGps(obj, index);
        setName(obj, index);
        setState(obj, index);
        setZip(obj, index);
        return obj;
    }
    
    public void LocationProfileDataOnDemand.setCity(LocationProfile obj, int index) {
        String city = "city_" + index;
        obj.setCity(city);
    }
    
    public void LocationProfileDataOnDemand.setCountry(LocationProfile obj, int index) {
        String country = "country_" + index;
        obj.setCountry(country);
    }
    
    public void LocationProfileDataOnDemand.setDescription(LocationProfile obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void LocationProfileDataOnDemand.setGps(LocationProfile obj, int index) {
        String gps = "gps_" + index;
        obj.setGps(gps);
    }
    
    public void LocationProfileDataOnDemand.setName(LocationProfile obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void LocationProfileDataOnDemand.setState(LocationProfile obj, int index) {
        String state = "state_" + index;
        obj.setState(state);
    }
    
    public void LocationProfileDataOnDemand.setZip(LocationProfile obj, int index) {
        String zip = "zip_" + index;
        obj.setZip(zip);
    }
    
    public LocationProfile LocationProfileDataOnDemand.getSpecificLocationProfile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LocationProfile obj = data.get(index);
        Long id = obj.getId();
        return LocationProfile.findLocationProfile(id);
    }
    
    public LocationProfile LocationProfileDataOnDemand.getRandomLocationProfile() {
        init();
        LocationProfile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return LocationProfile.findLocationProfile(id);
    }
    
    public boolean LocationProfileDataOnDemand.modifyLocationProfile(LocationProfile obj) {
        return false;
    }
    
    public void LocationProfileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LocationProfile.findLocationProfileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LocationProfile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LocationProfile>();
        for (int i = 0; i < 10; i++) {
            LocationProfile obj = getNewTransientLocationProfile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
