// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.OccupationProfileIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OccupationProfileIntegrationTest_Roo_Configurable {
    
    declare @type: OccupationProfileIntegrationTest: @Configurable;
    
}
