// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.TagProfile;
import com.advmon.webapp.datamodel.profiles.TagProfileDataOnDemand;
import com.advmon.webapp.datamodel.profiles.TagProfileIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TagProfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TagProfileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TagProfileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TagProfileIntegrationTest: @Transactional;
    
    @Autowired
    TagProfileDataOnDemand TagProfileIntegrationTest.dod;
    
    @Test
    public void TagProfileIntegrationTest.testCountTagProfiles() {
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", dod.getRandomTagProfile());
        long count = TagProfile.countTagProfiles();
        Assert.assertTrue("Counter for 'TagProfile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TagProfileIntegrationTest.testFindTagProfile() {
        TagProfile obj = dod.getRandomTagProfile();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to provide an identifier", id);
        obj = TagProfile.findTagProfile(id);
        Assert.assertNotNull("Find method for 'TagProfile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TagProfile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TagProfileIntegrationTest.testFindAllTagProfiles() {
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", dod.getRandomTagProfile());
        long count = TagProfile.countTagProfiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'TagProfile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TagProfile> result = TagProfile.findAllTagProfiles();
        Assert.assertNotNull("Find all method for 'TagProfile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TagProfile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TagProfileIntegrationTest.testFindTagProfileEntries() {
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", dod.getRandomTagProfile());
        long count = TagProfile.countTagProfiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TagProfile> result = TagProfile.findTagProfileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TagProfile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TagProfile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TagProfileIntegrationTest.testFlush() {
        TagProfile obj = dod.getRandomTagProfile();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to provide an identifier", id);
        obj = TagProfile.findTagProfile(id);
        Assert.assertNotNull("Find method for 'TagProfile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTagProfile(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TagProfile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TagProfileIntegrationTest.testMergeUpdate() {
        TagProfile obj = dod.getRandomTagProfile();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to provide an identifier", id);
        obj = TagProfile.findTagProfile(id);
        boolean modified =  dod.modifyTagProfile(obj);
        Integer currentVersion = obj.getVersion();
        TagProfile merged = (TagProfile)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TagProfile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TagProfileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", dod.getRandomTagProfile());
        TagProfile obj = dod.getNewTransientTagProfile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TagProfile' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TagProfile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TagProfileIntegrationTest.testRemove() {
        TagProfile obj = dod.getRandomTagProfile();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TagProfile' failed to provide an identifier", id);
        obj = TagProfile.findTagProfile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TagProfile' with identifier '" + id + "'", TagProfile.findTagProfile(id));
    }
    
}
