// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.profiles;

import com.advmon.webapp.datamodel.profiles.TagProfile;
import com.advmon.webapp.datamodel.profiles.TagProfileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TagProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TagProfileDataOnDemand: @Component;
    
    private Random TagProfileDataOnDemand.rnd = new SecureRandom();
    
    private List<TagProfile> TagProfileDataOnDemand.data;
    
    public TagProfile TagProfileDataOnDemand.getNewTransientTagProfile(int index) {
        TagProfile obj = new TagProfile();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void TagProfileDataOnDemand.setDescription(TagProfile obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void TagProfileDataOnDemand.setName(TagProfile obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public TagProfile TagProfileDataOnDemand.getSpecificTagProfile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TagProfile obj = data.get(index);
        Long id = obj.getId();
        return TagProfile.findTagProfile(id);
    }
    
    public TagProfile TagProfileDataOnDemand.getRandomTagProfile() {
        init();
        TagProfile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TagProfile.findTagProfile(id);
    }
    
    public boolean TagProfileDataOnDemand.modifyTagProfile(TagProfile obj) {
        return false;
    }
    
    public void TagProfileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TagProfile.findTagProfileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TagProfile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TagProfile>();
        for (int i = 0; i < 10; i++) {
            TagProfile obj = getNewTransientTagProfile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
