// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.AdvertisementDataOnDemand;
import com.advmon.webapp.datamodel.content.AdContent;
import com.advmon.webapp.datamodel.content.AdContentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AdContentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AdContentDataOnDemand: @Component;
    
    private Random AdContentDataOnDemand.rnd = new SecureRandom();
    
    private List<AdContent> AdContentDataOnDemand.data;
    
    @Autowired
    AdvertisementDataOnDemand AdContentDataOnDemand.advertisementDataOnDemand;
    
    public AdContent AdContentDataOnDemand.getNewTransientAdContent(int index) {
        AdContent obj = new AdContent();
        setText(obj, index);
        return obj;
    }
    
    public void AdContentDataOnDemand.setText(AdContent obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public AdContent AdContentDataOnDemand.getSpecificAdContent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AdContent obj = data.get(index);
        Long id = obj.getId();
        return AdContent.findAdContent(id);
    }
    
    public AdContent AdContentDataOnDemand.getRandomAdContent() {
        init();
        AdContent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AdContent.findAdContent(id);
    }
    
    public boolean AdContentDataOnDemand.modifyAdContent(AdContent obj) {
        return false;
    }
    
    public void AdContentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AdContent.findAdContentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AdContent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AdContent>();
        for (int i = 0; i < 10; i++) {
            AdContent obj = getNewTransientAdContent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
