// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.AdvertisementDataOnDemand;
import com.advmon.webapp.datamodel.content.AudioContent;
import com.advmon.webapp.datamodel.content.AudioContentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AudioContentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AudioContentDataOnDemand: @Component;
    
    private Random AudioContentDataOnDemand.rnd = new SecureRandom();
    
    private List<AudioContent> AudioContentDataOnDemand.data;
    
    @Autowired
    AdvertisementDataOnDemand AudioContentDataOnDemand.advertisementDataOnDemand;
    
    public AudioContent AudioContentDataOnDemand.getNewTransientAudioContent(int index) {
        AudioContent obj = new AudioContent();
        setAudioURL(obj, index);
        setText(obj, index);
        return obj;
    }
    
    public void AudioContentDataOnDemand.setAudioURL(AudioContent obj, int index) {
        String audioURL = "audioURL_" + index;
        obj.setAudioURL(audioURL);
    }
    
    public void AudioContentDataOnDemand.setText(AudioContent obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public AudioContent AudioContentDataOnDemand.getSpecificAudioContent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AudioContent obj = data.get(index);
        Long id = obj.getId();
        return AudioContent.findAudioContent(id);
    }
    
    public AudioContent AudioContentDataOnDemand.getRandomAudioContent() {
        init();
        AudioContent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AudioContent.findAudioContent(id);
    }
    
    public boolean AudioContentDataOnDemand.modifyAudioContent(AudioContent obj) {
        return false;
    }
    
    public void AudioContentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AudioContent.findAudioContentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AudioContent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AudioContent>();
        for (int i = 0; i < 10; i++) {
            AudioContent obj = getNewTransientAudioContent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
