// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.content.AudioContentIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AudioContentIntegrationTest_Roo_Configurable {
    
    declare @type: AudioContentIntegrationTest: @Configurable;
    
}
