// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.content.AudioContent;
import com.advmon.webapp.datamodel.content.AudioContentDataOnDemand;
import com.advmon.webapp.datamodel.content.AudioContentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AudioContentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AudioContentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AudioContentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AudioContentIntegrationTest: @Transactional;
    
    @Autowired
    AudioContentDataOnDemand AudioContentIntegrationTest.dod;
    
    @Test
    public void AudioContentIntegrationTest.testCountAudioContents() {
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", dod.getRandomAudioContent());
        long count = AudioContent.countAudioContents();
        Assert.assertTrue("Counter for 'AudioContent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AudioContentIntegrationTest.testFindAudioContent() {
        AudioContent obj = dod.getRandomAudioContent();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to provide an identifier", id);
        obj = AudioContent.findAudioContent(id);
        Assert.assertNotNull("Find method for 'AudioContent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AudioContent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AudioContentIntegrationTest.testFindAllAudioContents() {
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", dod.getRandomAudioContent());
        long count = AudioContent.countAudioContents();
        Assert.assertTrue("Too expensive to perform a find all test for 'AudioContent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AudioContent> result = AudioContent.findAllAudioContents();
        Assert.assertNotNull("Find all method for 'AudioContent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AudioContent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AudioContentIntegrationTest.testFindAudioContentEntries() {
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", dod.getRandomAudioContent());
        long count = AudioContent.countAudioContents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AudioContent> result = AudioContent.findAudioContentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AudioContent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AudioContent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AudioContentIntegrationTest.testFlush() {
        AudioContent obj = dod.getRandomAudioContent();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to provide an identifier", id);
        obj = AudioContent.findAudioContent(id);
        Assert.assertNotNull("Find method for 'AudioContent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAudioContent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AudioContent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AudioContentIntegrationTest.testMergeUpdate() {
        AudioContent obj = dod.getRandomAudioContent();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to provide an identifier", id);
        obj = AudioContent.findAudioContent(id);
        boolean modified =  dod.modifyAudioContent(obj);
        Integer currentVersion = obj.getVersion();
        AudioContent merged = (AudioContent)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AudioContent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AudioContentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", dod.getRandomAudioContent());
        AudioContent obj = dod.getNewTransientAudioContent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AudioContent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AudioContent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AudioContentIntegrationTest.testRemove() {
        AudioContent obj = dod.getRandomAudioContent();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AudioContent' failed to provide an identifier", id);
        obj = AudioContent.findAudioContent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AudioContent' with identifier '" + id + "'", AudioContent.findAudioContent(id));
    }
    
}
