// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.content.ImageContent;
import com.advmon.webapp.datamodel.content.ImageContentDataOnDemand;
import com.advmon.webapp.datamodel.content.ImageContentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ImageContentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ImageContentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ImageContentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ImageContentIntegrationTest: @Transactional;
    
    @Autowired
    ImageContentDataOnDemand ImageContentIntegrationTest.dod;
    
    @Test
    public void ImageContentIntegrationTest.testCountImageContents() {
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", dod.getRandomImageContent());
        long count = ImageContent.countImageContents();
        Assert.assertTrue("Counter for 'ImageContent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ImageContentIntegrationTest.testFindImageContent() {
        ImageContent obj = dod.getRandomImageContent();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to provide an identifier", id);
        obj = ImageContent.findImageContent(id);
        Assert.assertNotNull("Find method for 'ImageContent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ImageContent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ImageContentIntegrationTest.testFindAllImageContents() {
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", dod.getRandomImageContent());
        long count = ImageContent.countImageContents();
        Assert.assertTrue("Too expensive to perform a find all test for 'ImageContent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ImageContent> result = ImageContent.findAllImageContents();
        Assert.assertNotNull("Find all method for 'ImageContent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ImageContent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ImageContentIntegrationTest.testFindImageContentEntries() {
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", dod.getRandomImageContent());
        long count = ImageContent.countImageContents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ImageContent> result = ImageContent.findImageContentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ImageContent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ImageContent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ImageContentIntegrationTest.testFlush() {
        ImageContent obj = dod.getRandomImageContent();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to provide an identifier", id);
        obj = ImageContent.findImageContent(id);
        Assert.assertNotNull("Find method for 'ImageContent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyImageContent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ImageContent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageContentIntegrationTest.testMergeUpdate() {
        ImageContent obj = dod.getRandomImageContent();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to provide an identifier", id);
        obj = ImageContent.findImageContent(id);
        boolean modified =  dod.modifyImageContent(obj);
        Integer currentVersion = obj.getVersion();
        ImageContent merged = (ImageContent)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ImageContent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageContentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", dod.getRandomImageContent());
        ImageContent obj = dod.getNewTransientImageContent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ImageContent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ImageContent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ImageContentIntegrationTest.testRemove() {
        ImageContent obj = dod.getRandomImageContent();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageContent' failed to provide an identifier", id);
        obj = ImageContent.findImageContent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ImageContent' with identifier '" + id + "'", ImageContent.findImageContent(id));
    }
    
}
