// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.content.VideoContent;
import com.advmon.webapp.datamodel.content.VideoContentDataOnDemand;
import com.advmon.webapp.datamodel.content.VideoContentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VideoContentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VideoContentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VideoContentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VideoContentIntegrationTest: @Transactional;
    
    @Autowired
    VideoContentDataOnDemand VideoContentIntegrationTest.dod;
    
    @Test
    public void VideoContentIntegrationTest.testCountVideoContents() {
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", dod.getRandomVideoContent());
        long count = VideoContent.countVideoContents();
        Assert.assertTrue("Counter for 'VideoContent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VideoContentIntegrationTest.testFindVideoContent() {
        VideoContent obj = dod.getRandomVideoContent();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to provide an identifier", id);
        obj = VideoContent.findVideoContent(id);
        Assert.assertNotNull("Find method for 'VideoContent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VideoContent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VideoContentIntegrationTest.testFindAllVideoContents() {
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", dod.getRandomVideoContent());
        long count = VideoContent.countVideoContents();
        Assert.assertTrue("Too expensive to perform a find all test for 'VideoContent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VideoContent> result = VideoContent.findAllVideoContents();
        Assert.assertNotNull("Find all method for 'VideoContent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VideoContent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VideoContentIntegrationTest.testFindVideoContentEntries() {
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", dod.getRandomVideoContent());
        long count = VideoContent.countVideoContents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VideoContent> result = VideoContent.findVideoContentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VideoContent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VideoContent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VideoContentIntegrationTest.testFlush() {
        VideoContent obj = dod.getRandomVideoContent();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to provide an identifier", id);
        obj = VideoContent.findVideoContent(id);
        Assert.assertNotNull("Find method for 'VideoContent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVideoContent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VideoContent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VideoContentIntegrationTest.testMergeUpdate() {
        VideoContent obj = dod.getRandomVideoContent();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to provide an identifier", id);
        obj = VideoContent.findVideoContent(id);
        boolean modified =  dod.modifyVideoContent(obj);
        Integer currentVersion = obj.getVersion();
        VideoContent merged = (VideoContent)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'VideoContent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VideoContentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", dod.getRandomVideoContent());
        VideoContent obj = dod.getNewTransientVideoContent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VideoContent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VideoContent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VideoContentIntegrationTest.testRemove() {
        VideoContent obj = dod.getRandomVideoContent();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VideoContent' failed to provide an identifier", id);
        obj = VideoContent.findVideoContent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VideoContent' with identifier '" + id + "'", VideoContent.findVideoContent(id));
    }
    
}
