// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.AdvertisementDataOnDemand;
import com.advmon.webapp.datamodel.content.VideoContent;
import com.advmon.webapp.datamodel.content.VideoContentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VideoContentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VideoContentDataOnDemand: @Component;
    
    private Random VideoContentDataOnDemand.rnd = new SecureRandom();
    
    private List<VideoContent> VideoContentDataOnDemand.data;
    
    @Autowired
    AdvertisementDataOnDemand VideoContentDataOnDemand.advertisementDataOnDemand;
    
    public VideoContent VideoContentDataOnDemand.getNewTransientVideoContent(int index) {
        VideoContent obj = new VideoContent();
        setText(obj, index);
        setYouTubeURL(obj, index);
        return obj;
    }
    
    public void VideoContentDataOnDemand.setText(VideoContent obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public void VideoContentDataOnDemand.setYouTubeURL(VideoContent obj, int index) {
        String youTubeURL = "youTubeURL_" + index;
        obj.setYouTubeURL(youTubeURL);
    }
    
    public VideoContent VideoContentDataOnDemand.getSpecificVideoContent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        VideoContent obj = data.get(index);
        Long id = obj.getId();
        return VideoContent.findVideoContent(id);
    }
    
    public VideoContent VideoContentDataOnDemand.getRandomVideoContent() {
        init();
        VideoContent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return VideoContent.findVideoContent(id);
    }
    
    public boolean VideoContentDataOnDemand.modifyVideoContent(VideoContent obj) {
        return false;
    }
    
    public void VideoContentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = VideoContent.findVideoContentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'VideoContent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<VideoContent>();
        for (int i = 0; i < 10; i++) {
            VideoContent obj = getNewTransientVideoContent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
