// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel;

import com.advmon.webapp.datamodel.AdCategory;
import com.advmon.webapp.datamodel.AdCategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AdCategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AdCategoryDataOnDemand: @Component;
    
    private Random AdCategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<AdCategory> AdCategoryDataOnDemand.data;
    
    public AdCategory AdCategoryDataOnDemand.getNewTransientAdCategory(int index) {
        AdCategory obj = new AdCategory();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void AdCategoryDataOnDemand.setDescription(AdCategory obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void AdCategoryDataOnDemand.setName(AdCategory obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public AdCategory AdCategoryDataOnDemand.getSpecificAdCategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AdCategory obj = data.get(index);
        Long id = obj.getId();
        return AdCategory.findAdCategory(id);
    }
    
    public AdCategory AdCategoryDataOnDemand.getRandomAdCategory() {
        init();
        AdCategory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AdCategory.findAdCategory(id);
    }
    
    public boolean AdCategoryDataOnDemand.modifyAdCategory(AdCategory obj) {
        return false;
    }
    
    public void AdCategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AdCategory.findAdCategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AdCategory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AdCategory>();
        for (int i = 0; i < 10; i++) {
            AdCategory obj = getNewTransientAdCategory(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
