// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel;

import com.advmon.webapp.datamodel.Advertisement;
import com.advmon.webapp.datamodel.AdvertisementDataOnDemand;
import com.advmon.webapp.datamodel.AdvertisementIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdvertisementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdvertisementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdvertisementIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AdvertisementIntegrationTest: @Transactional;
    
    @Autowired
    AdvertisementDataOnDemand AdvertisementIntegrationTest.dod;
    
    @Test
    public void AdvertisementIntegrationTest.testCountAdvertisements() {
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", dod.getRandomAdvertisement());
        long count = Advertisement.countAdvertisements();
        Assert.assertTrue("Counter for 'Advertisement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdvertisementIntegrationTest.testFindAdvertisement() {
        Advertisement obj = dod.getRandomAdvertisement();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to provide an identifier", id);
        obj = Advertisement.findAdvertisement(id);
        Assert.assertNotNull("Find method for 'Advertisement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Advertisement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdvertisementIntegrationTest.testFindAllAdvertisements() {
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", dod.getRandomAdvertisement());
        long count = Advertisement.countAdvertisements();
        Assert.assertTrue("Too expensive to perform a find all test for 'Advertisement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Advertisement> result = Advertisement.findAllAdvertisements();
        Assert.assertNotNull("Find all method for 'Advertisement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Advertisement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdvertisementIntegrationTest.testFindAdvertisementEntries() {
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", dod.getRandomAdvertisement());
        long count = Advertisement.countAdvertisements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Advertisement> result = Advertisement.findAdvertisementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Advertisement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Advertisement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdvertisementIntegrationTest.testFlush() {
        Advertisement obj = dod.getRandomAdvertisement();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to provide an identifier", id);
        obj = Advertisement.findAdvertisement(id);
        Assert.assertNotNull("Find method for 'Advertisement' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdvertisement(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Advertisement' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdvertisementIntegrationTest.testMergeUpdate() {
        Advertisement obj = dod.getRandomAdvertisement();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to provide an identifier", id);
        obj = Advertisement.findAdvertisement(id);
        boolean modified =  dod.modifyAdvertisement(obj);
        Integer currentVersion = obj.getVersion();
        Advertisement merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Advertisement' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdvertisementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", dod.getRandomAdvertisement());
        Advertisement obj = dod.getNewTransientAdvertisement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Advertisement' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Advertisement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdvertisementIntegrationTest.testRemove() {
        Advertisement obj = dod.getRandomAdvertisement();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertisement' failed to provide an identifier", id);
        obj = Advertisement.findAdvertisement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Advertisement' with identifier '" + id + "'", Advertisement.findAdvertisement(id));
    }
    
}
