// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel;

import com.advmon.webapp.datamodel.Advertiser;
import com.advmon.webapp.datamodel.AdvertiserDataOnDemand;
import com.advmon.webapp.datamodel.AdvertiserIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdvertiserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdvertiserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdvertiserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AdvertiserIntegrationTest: @Transactional;
    
    @Autowired
    AdvertiserDataOnDemand AdvertiserIntegrationTest.dod;
    
    @Test
    public void AdvertiserIntegrationTest.testCountAdvertisers() {
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", dod.getRandomAdvertiser());
        long count = Advertiser.countAdvertisers();
        Assert.assertTrue("Counter for 'Advertiser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdvertiserIntegrationTest.testFindAdvertiser() {
        Advertiser obj = dod.getRandomAdvertiser();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to provide an identifier", id);
        obj = Advertiser.findAdvertiser(id);
        Assert.assertNotNull("Find method for 'Advertiser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Advertiser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdvertiserIntegrationTest.testFindAllAdvertisers() {
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", dod.getRandomAdvertiser());
        long count = Advertiser.countAdvertisers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Advertiser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Advertiser> result = Advertiser.findAllAdvertisers();
        Assert.assertNotNull("Find all method for 'Advertiser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Advertiser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdvertiserIntegrationTest.testFindAdvertiserEntries() {
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", dod.getRandomAdvertiser());
        long count = Advertiser.countAdvertisers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Advertiser> result = Advertiser.findAdvertiserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Advertiser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Advertiser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdvertiserIntegrationTest.testFlush() {
        Advertiser obj = dod.getRandomAdvertiser();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to provide an identifier", id);
        obj = Advertiser.findAdvertiser(id);
        Assert.assertNotNull("Find method for 'Advertiser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdvertiser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Advertiser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdvertiserIntegrationTest.testMergeUpdate() {
        Advertiser obj = dod.getRandomAdvertiser();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to provide an identifier", id);
        obj = Advertiser.findAdvertiser(id);
        boolean modified =  dod.modifyAdvertiser(obj);
        Integer currentVersion = obj.getVersion();
        Advertiser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Advertiser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdvertiserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", dod.getRandomAdvertiser());
        Advertiser obj = dod.getNewTransientAdvertiser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Advertiser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Advertiser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdvertiserIntegrationTest.testRemove() {
        Advertiser obj = dod.getRandomAdvertiser();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Advertiser' failed to provide an identifier", id);
        obj = Advertiser.findAdvertiser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Advertiser' with identifier '" + id + "'", Advertiser.findAdvertiser(id));
    }
    
}
