// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel;

import com.advmon.webapp.datamodel.Advertisement;
import com.advmon.webapp.datamodel.AdvertisementDataOnDemand;
import com.advmon.webapp.datamodel.Advertiser;
import com.advmon.webapp.datamodel.AdvertiserDataOnDemand;
import com.advmon.webapp.datamodel.PaymentInfoDataOnDemand;
import com.advmon.webapp.datamodel.content.AdContentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AdvertisementDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AdvertisementDataOnDemand: @Component;
    
    private Random AdvertisementDataOnDemand.rnd = new SecureRandom();
    
    private List<Advertisement> AdvertisementDataOnDemand.data;
    
    @Autowired
    AdvertiserDataOnDemand AdvertisementDataOnDemand.advertiserDataOnDemand;
    
    @Autowired
    AdContentDataOnDemand AdvertisementDataOnDemand.adContentDataOnDemand;
    
    @Autowired
    PaymentInfoDataOnDemand AdvertisementDataOnDemand.paymentInfoDataOnDemand;
    
    public Advertisement AdvertisementDataOnDemand.getNewTransientAdvertisement(int index) {
        Advertisement obj = new Advertisement();
        setAdvertiser(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        setRecurrence(obj, index);
        return obj;
    }
    
    public void AdvertisementDataOnDemand.setAdvertiser(Advertisement obj, int index) {
        Advertiser advertiser = advertiserDataOnDemand.getRandomAdvertiser();
        obj.setAdvertiser(advertiser);
    }
    
    public void AdvertisementDataOnDemand.setDescription(Advertisement obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void AdvertisementDataOnDemand.setName(Advertisement obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void AdvertisementDataOnDemand.setRecurrence(Advertisement obj, int index) {
        int recurrence = index;
        obj.setRecurrence(recurrence);
    }
    
    public Advertisement AdvertisementDataOnDemand.getSpecificAdvertisement(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Advertisement obj = data.get(index);
        Long id = obj.getId();
        return Advertisement.findAdvertisement(id);
    }
    
    public Advertisement AdvertisementDataOnDemand.getRandomAdvertisement() {
        init();
        Advertisement obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Advertisement.findAdvertisement(id);
    }
    
    public boolean AdvertisementDataOnDemand.modifyAdvertisement(Advertisement obj) {
        return false;
    }
    
    public void AdvertisementDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Advertisement.findAdvertisementEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Advertisement' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Advertisement>();
        for (int i = 0; i < 10; i++) {
            Advertisement obj = getNewTransientAdvertisement(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
