// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel;

import com.advmon.webapp.datamodel.EndUser;
import com.advmon.webapp.datamodel.EndUserDataOnDemand;
import com.advmon.webapp.datamodel.MarketProfileHistory;
import com.advmon.webapp.datamodel.ProfileHistoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProfileHistoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProfileHistoryDataOnDemand: @Component;
    
    private Random ProfileHistoryDataOnDemand.rnd = new SecureRandom();
    
    private List<MarketProfileHistory> ProfileHistoryDataOnDemand.data;
    
    @Autowired
    EndUserDataOnDemand ProfileHistoryDataOnDemand.endUserDataOnDemand;
    
    public MarketProfileHistory ProfileHistoryDataOnDemand.getNewTransientMarketProfileHistory(int index) {
        MarketProfileHistory obj = new MarketProfileHistory();
        setEndTime(obj, index);
        setEndUser(obj, index);
        setStartTime(obj, index);
        return obj;
    }
    
    public void ProfileHistoryDataOnDemand.setEndTime(MarketProfileHistory obj, int index) {
        Long endTime = new Integer(index).longValue();
        obj.setEndTime(endTime);
    }
    
    public void ProfileHistoryDataOnDemand.setEndUser(MarketProfileHistory obj, int index) {
        EndUser endUser = endUserDataOnDemand.getRandomEndUser();
        obj.setEndUser(endUser);
    }
    
    public void ProfileHistoryDataOnDemand.setStartTime(MarketProfileHistory obj, int index) {
        Long startTime = new Integer(index).longValue();
        obj.setStartTime(startTime);
    }
    
    public MarketProfileHistory ProfileHistoryDataOnDemand.getSpecificMarketProfileHistory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MarketProfileHistory obj = data.get(index);
        Long id = obj.getId();
        return MarketProfileHistory.findMarketProfileHistory(id);
    }
    
    public MarketProfileHistory ProfileHistoryDataOnDemand.getRandomMarketProfileHistory() {
        init();
        MarketProfileHistory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MarketProfileHistory.findMarketProfileHistory(id);
    }
    
    public boolean ProfileHistoryDataOnDemand.modifyMarketProfileHistory(MarketProfileHistory obj) {
        return false;
    }
    
    public void ProfileHistoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MarketProfileHistory.findMarketProfileHistoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MarketProfileHistory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MarketProfileHistory>();
        for (int i = 0; i < 10; i++) {
            MarketProfileHistory obj = getNewTransientMarketProfileHistory(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
