// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel;

import com.advmon.webapp.datamodel.TargetMarketProfile;
import com.advmon.webapp.datamodel.TargetMarketProfileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TargetMarketProfileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TargetMarketProfileDataOnDemand: @Component;
    
    private Random TargetMarketProfileDataOnDemand.rnd = new SecureRandom();
    
    private List<TargetMarketProfile> TargetMarketProfileDataOnDemand.data;
    
    public TargetMarketProfile TargetMarketProfileDataOnDemand.getNewTransientTargetMarketProfile(int index) {
        TargetMarketProfile obj = new TargetMarketProfile();
        setDescription(obj, index);
        setSegmentName(obj, index);
        return obj;
    }
    
    public void TargetMarketProfileDataOnDemand.setDescription(TargetMarketProfile obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void TargetMarketProfileDataOnDemand.setSegmentName(TargetMarketProfile obj, int index) {
        String segmentName = "segmentName_" + index;
        obj.setSegmentName(segmentName);
    }
    
    public TargetMarketProfile TargetMarketProfileDataOnDemand.getSpecificTargetMarketProfile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TargetMarketProfile obj = data.get(index);
        Long id = obj.getId();
        return TargetMarketProfile.findTargetMarketProfile(id);
    }
    
    public TargetMarketProfile TargetMarketProfileDataOnDemand.getRandomTargetMarketProfile() {
        init();
        TargetMarketProfile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TargetMarketProfile.findTargetMarketProfile(id);
    }
    
    public boolean TargetMarketProfileDataOnDemand.modifyTargetMarketProfile(TargetMarketProfile obj) {
        return false;
    }
    
    public void TargetMarketProfileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TargetMarketProfile.findTargetMarketProfileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TargetMarketProfile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TargetMarketProfile>();
        for (int i = 0; i < 10; i++) {
            TargetMarketProfile obj = getNewTransientTargetMarketProfile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
