// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.etc;

import com.advmon.webapp.datamodel.etc.IntRange;
import com.advmon.webapp.datamodel.etc.IntRangeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect IntRangeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IntRangeDataOnDemand: @Component;
    
    private Random IntRangeDataOnDemand.rnd = new SecureRandom();
    
    private List<IntRange> IntRangeDataOnDemand.data;
    
    public IntRange IntRangeDataOnDemand.getNewTransientIntRange(int index) {
        IntRange obj = new IntRange();
        setDescription(obj, index);
        setMax(obj, index);
        setMin(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void IntRangeDataOnDemand.setDescription(IntRange obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void IntRangeDataOnDemand.setMax(IntRange obj, int index) {
        Integer max = new Integer(index);
        obj.setMax(max);
    }
    
    public void IntRangeDataOnDemand.setMin(IntRange obj, int index) {
        Integer min = new Integer(index);
        obj.setMin(min);
    }
    
    public void IntRangeDataOnDemand.setName(IntRange obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public IntRange IntRangeDataOnDemand.getSpecificIntRange(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        IntRange obj = data.get(index);
        Long id = obj.getId();
        return IntRange.findIntRange(id);
    }
    
    public IntRange IntRangeDataOnDemand.getRandomIntRange() {
        init();
        IntRange obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return IntRange.findIntRange(id);
    }
    
    public boolean IntRangeDataOnDemand.modifyIntRange(IntRange obj) {
        return false;
    }
    
    public void IntRangeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = IntRange.findIntRangeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'IntRange' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<IntRange>();
        for (int i = 0; i < 10; i++) {
            IntRange obj = getNewTransientIntRange(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
