// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.etc;

import com.advmon.webapp.datamodel.etc.LongRange;
import com.advmon.webapp.datamodel.etc.LongRangeDataOnDemand;
import com.advmon.webapp.datamodel.etc.LongRangeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LongRangeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LongRangeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LongRangeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LongRangeIntegrationTest: @Transactional;
    
    @Autowired
    LongRangeDataOnDemand LongRangeIntegrationTest.dod;
    
    @Test
    public void LongRangeIntegrationTest.testCountLongRanges() {
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", dod.getRandomLongRange());
        long count = LongRange.countLongRanges();
        Assert.assertTrue("Counter for 'LongRange' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LongRangeIntegrationTest.testFindLongRange() {
        LongRange obj = dod.getRandomLongRange();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to provide an identifier", id);
        obj = LongRange.findLongRange(id);
        Assert.assertNotNull("Find method for 'LongRange' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LongRange' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LongRangeIntegrationTest.testFindAllLongRanges() {
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", dod.getRandomLongRange());
        long count = LongRange.countLongRanges();
        Assert.assertTrue("Too expensive to perform a find all test for 'LongRange', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LongRange> result = LongRange.findAllLongRanges();
        Assert.assertNotNull("Find all method for 'LongRange' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LongRange' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LongRangeIntegrationTest.testFindLongRangeEntries() {
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", dod.getRandomLongRange());
        long count = LongRange.countLongRanges();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LongRange> result = LongRange.findLongRangeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LongRange' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LongRange' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LongRangeIntegrationTest.testFlush() {
        LongRange obj = dod.getRandomLongRange();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to provide an identifier", id);
        obj = LongRange.findLongRange(id);
        Assert.assertNotNull("Find method for 'LongRange' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLongRange(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LongRange' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LongRangeIntegrationTest.testMergeUpdate() {
        LongRange obj = dod.getRandomLongRange();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to provide an identifier", id);
        obj = LongRange.findLongRange(id);
        boolean modified =  dod.modifyLongRange(obj);
        Integer currentVersion = obj.getVersion();
        LongRange merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LongRange' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LongRangeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", dod.getRandomLongRange());
        LongRange obj = dod.getNewTransientLongRange(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LongRange' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LongRange' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LongRange' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LongRangeIntegrationTest.testRemove() {
        LongRange obj = dod.getRandomLongRange();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LongRange' failed to provide an identifier", id);
        obj = LongRange.findLongRange(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LongRange' with identifier '" + id + "'", LongRange.findLongRange(id));
    }
    
}
