// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel;

import com.advmon.webapp.datamodel.Advertiser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Advertiser_Roo_Configurable {
    
    declare @type: Advertiser: @Configurable;
    
}
