// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.etc;

import com.advmon.webapp.datamodel.etc.LongRange;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LongRange_Roo_Configurable {
    
    declare @type: LongRange: @Configurable;
    
}
