// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.advmon.webapp.datamodel.content;

import com.advmon.webapp.datamodel.content.AudioContent;
import javax.persistence.Entity;

privileged aspect AudioContent_Roo_Jpa_Entity {
    
    declare @type: AudioContent: @Entity;
    
}
